### ISSUE TITLE
Documentation & fixes

### ISSUE THREAD

**Issue by LuisBoto** [MasterCloudApps-Projects/chess#13]
- [x] Explicitly indicate factory functions shouldn't make use of private functions or attributes (they turn into closures)
- [x] Expand info on closures using 'that' context
  - [x] Reference to Douglas Crockford's book on this/that  
- [x] Module pattern info / reference on singleton
- [x] Add UML diagrams on main documentation
- [x] Add testing & test case documentation

- [x] More tests 
- [x] Remove decorator in favor of 'getNextStrategy' method on strategies (make a release previously)

**Comment by lmorente** [comment]
I have found the book and used it for some references in the closure, but have not seen the use of that.

https://media.oiipdf.com/pdf/ceabcdca-01c2-4f97-95dd-a577f08b9169.pdf

I have added a brief explanation to the that but it remains to be supplemented with references.

**Comment by lmorente** [comment]
Created tag and release
![image](https://user-images.githubusercontent.com/85077458/201422536-cd54a5d1-17ce-4990-b39b-b99df37578f2.png)

![image](https://user-images.githubusercontent.com/85077458/201422682-9eaf3b47-6cac-4758-b41a-13bcf59b56d0.png)

**Comment by lmorente** [comment]
An excel in drive has been created for the documentation of the test cases. A description of the tests carried out and the library used, as well as a brief description of the test cases, will be indicated in the report. The excel is provided as an annex

https://docs.google.com/spreadsheets/d/1NxIL9fISkHMKtSH49MPgliHf_3dPL7Ml2G4Gr1NfhgI/edit#gid=0
